name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  discussions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          path: packages/client
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      # Publish to npm if a new release was created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build and publish
        run: |
          cd packages/client
          pnpm build
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
